touch 01-introduction.rst
touch 02-problem-statemant.rst
touch 03-build-tempate-web-application.rst
touch 04-generate-jpa-entities.rst
touch 05-query-database-from-servlet.rst
touch 06-active-redeploy.rst
touch 07-query-database-using-ejb.rst
touch 08-add-values-to-database-using-ejb.rst
touch 09-type-safe-criteria-query.rst
touch 10-caching-using-singleton-ejb.rst
touch 11-mvc-using-fsf2-facelets-based-view.rst
touch 12-dry-using-jsf2-component.rst
touch 13-declarative-ajax-.rst
touch 14-publish-ejb-as-resfull-resource-using-jax-rs.rst
touch 15-jersey-client-api-to-access-restful-resource.rst
touch 16-inject-beans-using-cdi-qualifiers.rst
touch 17-cross-cutting-concerns-using-cdi-interceptors.rst
touch 18-observer-pattern-using-cdi-events.rst
touch 19-conclusion.rst
touch 20-troubleshooting.rst
touch 21-acknowledgments.rst
touch 22-completed-solutions.rst